table 'Ads Insights'
	lineageTag: c648c534-838e-470d-bdde-278ca1446342

	column 'Act Id Conta de Anúncio'
		dataType: string
		lineageTag: fc4b430f-6162-4c26-abc4-5d6975ea7b46
		summarizeBy: none
		sourceColumn: Act Id Conta de Anúncio

		annotation SummarizationSetBy = Automatic

	column account_id
		dataType: string
		lineageTag: be289f49-6dde-490b-b97c-7d2bba4f1413
		summarizeBy: none
		sourceColumn: account_id

		annotation SummarizationSetBy = Automatic

	column campaign_id
		dataType: string
		lineageTag: 8089ead4-f6a5-4987-83e7-d1bcc32c96db
		summarizeBy: none
		sourceColumn: campaign_id

		annotation SummarizationSetBy = Automatic

	column adset_id
		dataType: string
		lineageTag: 852600ab-6575-4d9b-bd1b-b604277b6d6f
		summarizeBy: none
		sourceColumn: adset_id

		annotation SummarizationSetBy = Automatic

	column ad_id
		dataType: string
		lineageTag: af424b75-d1d2-4ef8-a4e6-83f45354e4ae
		summarizeBy: none
		sourceColumn: ad_id

		annotation SummarizationSetBy = Automatic

	column date_start
		dataType: string
		lineageTag: 08104061-652a-4f23-a56c-ffc767f71fac
		summarizeBy: none
		sourceColumn: date_start

		annotation SummarizationSetBy = Automatic

	column date_stop
		dataType: string
		lineageTag: d9f352fa-3283-4d25-bd02-57760a8e98b8
		summarizeBy: none
		sourceColumn: date_stop

		annotation SummarizationSetBy = Automatic

	column spend
		dataType: string
		lineageTag: ca8745f5-d99c-4442-83da-a525935ed02c
		summarizeBy: none
		sourceColumn: spend

		annotation SummarizationSetBy = Automatic

	column account_currency
		dataType: string
		lineageTag: 2f475911-ecd6-4495-9dc6-58988398337c
		summarizeBy: none
		sourceColumn: account_currency

		annotation SummarizationSetBy = Automatic

	column reach
		dataType: string
		lineageTag: 9ccb1672-95d9-4710-a9dc-e493b10242ee
		summarizeBy: none
		sourceColumn: reach

		annotation SummarizationSetBy = Automatic

	column impressions
		dataType: string
		lineageTag: d22ee496-c97b-4820-abee-68ca5437ce2a
		summarizeBy: none
		sourceColumn: impressions

		annotation SummarizationSetBy = Automatic

	column frequency
		dataType: string
		lineageTag: f0762e14-f1ed-4605-9233-f3f0a5fba0b2
		summarizeBy: none
		sourceColumn: frequency

		annotation SummarizationSetBy = Automatic

	column inline_link_clicks
		dataType: string
		lineageTag: 74060ccd-a77c-46cf-b77f-979f416b37c2
		summarizeBy: none
		sourceColumn: inline_link_clicks

		annotation SummarizationSetBy = Automatic

	column clicks
		dataType: string
		lineageTag: 4e10bb70-f85f-4d78-9843-e4cade02d3c6
		summarizeBy: none
		sourceColumn: clicks

		annotation SummarizationSetBy = Automatic

	column inline_post_engagement
		dataType: string
		lineageTag: 8d40c556-d6d8-4cae-aaf6-1939102f4f86
		summarizeBy: none
		sourceColumn: inline_post_engagement

		annotation SummarizationSetBy = Automatic

	column api_cursor
		dataType: string
		lineageTag: 733e5e7d-57c5-4e4e-b845-0f57f912014e
		summarizeBy: none
		sourceColumn: api_cursor

		annotation SummarizationSetBy = Automatic

	column 'Data Inicial'
		dataType: string
		lineageTag: c1259b6f-a900-485c-b631-f4110beb290e
		summarizeBy: none
		sourceColumn: Data Inicial

		annotation SummarizationSetBy = Automatic

	column 'Data Final'
		dataType: string
		lineageTag: c72ae95e-6cf3-4a17-b718-d93b8b88637c
		summarizeBy: none
		sourceColumn: Data Final

		annotation SummarizationSetBy = Automatic

	partition 'Ads Insights' = m
		mode: import
		source =
				let
				    Source = list_of_accounts_and_dates,
				    #"Invoked Custom Function" = Table.AddColumn(Source, "API Data", each Fn_get_ads_insights([Act Id Conta de Anúncio], [Data Inicial], [Data Final])),
				    #"Expanded API Data" = Table.ExpandListColumn(#"Invoked Custom Function", "API Data"),
				    #"Expanded API Data1" = Table.ExpandTableColumn(#"Expanded API Data", "API Data", {"api_data", "api_cursor"}, {"api_data", "api_cursor"}),
				    #"Expanded api_data" = Table.ExpandListColumn(#"Expanded API Data1", "api_data"),
				    #"Expanded api_data1" = Table.ExpandRecordColumn(#"Expanded api_data", "api_data", {"account_id", "campaign_id", "adset_id", "ad_id", "date_start", "date_stop", "spend", "account_currency", "reach", "impressions", "frequency", "inline_link_clicks", "clicks", "inline_post_engagement"}, {"account_id", "campaign_id", "adset_id", "ad_id", "date_start", "date_stop", "spend", "account_currency", "reach", "impressions", "frequency", "inline_link_clicks", "clicks", "inline_post_engagement"})
				in
				    #"Expanded api_data1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

