table Anúncios
	lineageTag: 59e36885-e862-4568-a5a3-245fe479ea1e

	column 'Id Act Conta de Anúncio'
		dataType: string
		lineageTag: 64612710-ee36-4799-b25a-607c9803b109
		summarizeBy: none
		sourceColumn: Id Act Conta de Anúncio

		annotation SummarizationSetBy = Automatic

	column 'Id Conta de Anúncio'
		dataType: int64
		formatString: 0
		lineageTag: ccabbc82-7aac-4a08-9ec8-7cb1364e3e58
		summarizeBy: sum
		sourceColumn: Id Conta de Anúncio

		annotation SummarizationSetBy = Automatic

	column 'Id Campanha'
		dataType: int64
		formatString: 0
		lineageTag: 118fc8eb-309b-4231-a8e0-99cfa39d5329
		summarizeBy: sum
		sourceColumn: Id Campanha

		annotation SummarizationSetBy = Automatic

	column 'Id Conjunto de Anúncio'
		dataType: int64
		formatString: 0
		lineageTag: 02621ae1-5a4e-455b-a634-324a42b830d0
		summarizeBy: sum
		sourceColumn: Id Conjunto de Anúncio

		annotation SummarizationSetBy = Automatic

	column 'Id Anúncio'
		dataType: int64
		formatString: 0
		lineageTag: 5d5aa158-ae43-4ac9-b308-2fe771fa9159
		summarizeBy: sum
		sourceColumn: Id Anúncio

		annotation SummarizationSetBy = Automatic

	column Anúncio
		dataType: string
		lineageTag: e560cf17-4780-42d5-8ccb-5a439bc5fa8c
		summarizeBy: none
		sourceColumn: Anúncio

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 1d72ec10-ae72-49bd-af62-2912110da672
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column 'Data de Criação'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 19ef91b0-6031-4505-a8c4-c8529c91ab1f
		summarizeBy: none
		sourceColumn: Data de Criação

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Data da Última Atualização'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 3f3076c3-fcf8-4bb7-aadd-43bea352af72
		summarizeBy: none
		sourceColumn: Data da Última Atualização

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Id Anúncio Fonte'
		dataType: int64
		formatString: 0
		lineageTag: 8e7ccfdf-3f29-4b95-87d8-7a4dc9fc9016
		summarizeBy: sum
		sourceColumn: Id Anúncio Fonte

		annotation SummarizationSetBy = Automatic

	column 'Id Criativo'
		dataType: int64
		formatString: 0
		lineageTag: daf6b3ad-67f9-4bd8-baad-0476f30ce0e9
		summarizeBy: sum
		sourceColumn: Id Criativo

		annotation SummarizationSetBy = Automatic

	partition Anúncios = m
		mode: import
		source = ```
				let
				// API parameters
				    Base_url = "https://graph.facebook.com/v18.0/",
				    Endpoint_url = "/ads",
				    Fields = "account_id,campaign_id,adset_id,id,name,status,created_time,updated_time,source_ad_id,creative{id}",
				    Limit = "1000",
				    Date_preset = "last_7d",
				            
				// Get API data functions
				    fn_get_api_data = ( Adaccount_id as text, Page_cursor as text) =>
				        Json.Document(
				            Web.Contents( 
				                Base_url,
				                [
				                    RelativePath = Adaccount_id & Endpoint_url,
				                    Headers = [ Authorization = "Bearer " & access_token ], 
				                    Query = [ date_preset=Date_preset, fields=Fields, limit=Limit, after=Page_cursor ] 
				                ] 
				            )
				        ),
				
				// Get API paginated results
				    fn_get_api_data_loop = ( Adaccount_id as text ) =>
				        List.Generate(
				            () => [
				                api_data = fn_get_api_data( Adaccount_id , "" ),   // Adjust the addacoun parameter here
				                api_cursor = ""
				            ],
				            each List.Count( [api_data][data] ) > 0,
				            each [ 
				                api_data = fn_get_api_data( Adaccount_id , [api_data][paging][cursors][after] ),   // Adjust the addacoun parameter here
				                api_cursor = [api_data][paging][cursors][after]
				            ],
				            each Table.FromRecords({[ api_data = [api_data][data], api_cursor = [api_data][paging][cursors][after] ]})
				        ),
				        
				// Get data from all user ad account
				    Source = Table.AddColumn(customer_adaccounts, "API data", each fn_get_api_data_loop([Customer Ad Account])),
				    #"Expanded API data" = Table.ExpandListColumn(Source, "API data"),
				    #"Expanded API data1" = Table.ExpandTableColumn(#"Expanded API data", "API data", {"api_data", "api_cursor"}, {"api_data", "api_cursor"}),
				    #"Expanded api_data" = Table.ExpandListColumn(#"Expanded API data1", "api_data"),
				    #"Expanded api_data1" = Table.ExpandRecordColumn(#"Expanded api_data", "api_data", {"account_id", "campaign_id", "adset_id", "id", "name", "status", "created_time", "updated_time", "source_ad_id", "creative"}, {"account_id", "campaign_id", "adset_id", "id", "name", "status", "created_time", "updated_time", "source_ad_id", "creative"}),
				    #"Expanded creative" = Table.ExpandRecordColumn(#"Expanded api_data1", "creative", {"id"}, {"id.1"}),
				    #"Removed Columns" = Table.RemoveColumns(#"Expanded creative",{"api_cursor"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Removed Columns",{{"Customer Ad Account", type text}, {"account_id", Int64.Type}, {"campaign_id", Int64.Type}, {"adset_id", Int64.Type}, {"id", Int64.Type}, {"name", type text}, {"status", type text}, {"created_time", type datetimezone}, {"updated_time", type datetimezone}, {"source_ad_id", Int64.Type}, {"id.1", Int64.Type}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Customer Ad Account", "Id Act Conta de Anúncio"}, {"account_id", "Id Conta de Anúncio"}, {"campaign_id", "Id Campanha"}, {"adset_id", "Id Conjunto de Anúncio"}, {"id", "Id Anúncio"}, {"name", "Anúncio"}, {"status", "Status"}, {"created_time", "Data de Criação"}, {"updated_time", "Data da Última Atualização"}, {"source_ad_id", "Id Anúncio Fonte"}, {"id.1", "Id Criativo"}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Renamed Columns",{{"Data de Criação", type date}, {"Data da Última Atualização", type date}})
				in
				    #"Changed Type1"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

